version: 2
jobs:
  build:
    working_directory: /go/src/github.com/ta2mo/blog-maintenance
    docker:
      - image: circleci/golang:1.11
    environment:
      - GOCACHE: "/tmp/go/cache"
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ checksum "Gopkg.lock" }}
            - dep
      - run:
          name: ensure
          command: |
            if [ ! -d vendor ]; then
              if ! type dep >/dev/null 2>&1; then
                go get github.com/golang/dep/cmd/dep
              fi
              dep ensure
            fi
      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - save_cache:
          key: dep
          paths:
            - /go/bin/dep
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}--
            - build-cache-master--
            - build-cache-
      - run:
          name: build
          command: go build
      - save_cache:
          key: build-cache-{{ .Branch }}--{{ .Revision }}
          paths:
          - /tmp/go/cache
          when: on_fail
      - run:
          name: prepare cache dir if not exists
          command: mkdir -p $GOCACHE
      - persist_to_workspace:
          root: /
          paths:
            - tmp/go/cache
            - go/src/github.com/ta2mo/blog-maintenance/artifacts
  deploy:
    working_directory: /go/src/github.com/ta2mo/blog-maintenance
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: deploy
          command: echo "deploy"

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build