name: CI/CD

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          
      - name: Build
        run: go build
        
      - name: Convert
        run: ./blog-maintenance convert
        
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/src/github.com/ta2mo/blog-maintenance
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Upload nuxt-template as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuxt-template
          path: nuxt-template
          retention-days: 1

  generate:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download nuxt-template artifact
        uses: actions/download-artifact@v4
        with:
          name: nuxt-template
          path: nuxt-template
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install dependencies
        working-directory: nuxt-template
        run: |
          npm install
          npm install postcss-custom-properties --save-dev
        
      - name: Generate
        working-directory: nuxt-template
        run: |
          npm run generate
        
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: nuxt-template/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('nuxt-template/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Upload generated files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-files
          path: nuxt-template/.output/public
          retention-days: 1

  deploy:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download generated files
        uses: actions/download-artifact@v4
        with:
          name: generated-files
          path: generated-files
      
      - name: Clone target repository
        run: git clone --depth 1 https://${{ secrets.ACCESS_TOKEN }}@github.com/ta2mo/ta2mo.github.io.git
        
      - name: Copy generated files
        run: |
          cp -R generated-files/* ta2mo.github.io/
        
      - name: Deploy to GitHub Pages
        working-directory: ta2mo.github.io
        run: |
          git config user.email naoto.tanimoto@gmail.com
          git config user.name ta2mo
          git add --all
          git commit -m "update via github actions"
          git pull -q https://${{ secrets.ACCESS_TOKEN }}@github.com/ta2mo/ta2mo.github.io.git HEAD
          git push -q https://${{ secrets.ACCESS_TOKEN }}@github.com/ta2mo/ta2mo.github.io.git HEAD 
